# Application Configuration
app:
  env: development  # development, staging, production
  name: FreeFileConverterZ
  port: 3000
  secret: your-secret-key
  upload_dir: ./uploads
  max_upload_size: 104857600  # 100MB in bytes

# Database Configuration
database:
  driver: postgres
  host: localhost
  port: 5432
  name: freefileconverterz
  user: postgres
  password: postgres
  ssl_mode: disable
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 300  # in seconds

# Redis Configuration
redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5

# JWT Configuration
jwt:
  secret: your-jwt-secret-key
  expires_in: 24h  # e.g., 1h, 24h, 7d
  issuer: freefileconverterz

# File Storage (S3 compatible)
storage:
  provider: s3  # s3, local
  s3:
    endpoint: http://localhost:9000
    region: us-east-1
    bucket: freefileconverterz
    access_key: minioadmin
    secret_key: minioadmin
    use_ssl: false
    force_path_style: true

# Rate Limiting
rate_limit:
  enabled: true
  requests: 100  # requests per minute

# Logging
log:
  level: debug  # debug, info, warn, error, fatal, panic
  format: text  # text, json
  file: freefileconverterz.log

# Email Configuration (for notifications)
email:
  enabled: false
  provider: smtp  # smtp, sendgrid, aws_ses
  from: no-reply@freefileconverterz.com
  smtp:
    host: smtp.example.com
    port: 587
    username: your-username
    password: your-password
    encryption: tls  # tls, ssl, none

# External Services
external_services:
  # Google reCAPTCHA
  recaptcha:
    enabled: false
    site_key: your-site-key
    secret_key: your-secret-key
    min_score: 0.5

# Feature Flags
features:
  user_registration: true
  email_verification: false
  password_reset: true
  social_login: false
  api_documentation: true

# CORS Configuration
cors:
  allowed_origins:
    - http://localhost:3000
    - https://freefileconverterz.com
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed_headers:
    - Accept
    - Content-Type
    - Content-Length
    - Accept-Encoding
    - X-CSRF-Token
    - Authorization
  allow_credentials: true
  max_age: 300  # in seconds
