version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:8080"  # Backend API
    environment:
      - APP_ENV=development
      - PORT=8080
      - UPLOAD_PATH=/app/uploads
      - TEMP_PATH=/app/temp
      - MAX_UPLOAD_SIZE=104857600
      - STORAGE_PROVIDER=local
    volumes:
      - ./uploads:/app/uploads
      - ./temp:/app/temp
      - ./config:/app/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - VITE_API_URL=/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
